name: agriflow

description: AgriFlow - Clean Architecture Flutter App for agriculture supply chain.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  smooth_page_indicator: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logoS.png
    - assets/images/logo.png
    - assets/images/app1.png
    - assets/images/app2.png
    - assets/images/app3.png
    - assets/images/app4.png
    - assets/images/app5.png
    - assets/images/lettuce.jpg


  

    



